import React from 'react';

const PendingTradesData = [
  {
    account: 19843983,
    name: 'John Smith RRSP',
    client: 'John Smith',
    trades: 5,
    value: '$221,101 CAD',
    source: 'Rebalance',
    equitiesPrct: '57.5%',
    fixedIncomePrct: '40.0%',
    cashPrct: '2.5%',
    equitiesRec: [
      { 
        assetName: 'Russell Canadian Equity',
        targetPrct: '20%',
        currentMV: '$43,000',
        currentWeight: '19.8%',
        source: 'Rebalance',
        trades: '+ $2,000',
        postMV: '$45,000',
        postTargetPrct: '20%',
      },
      { 
        assetName: 'Mackenzie US Large Cap',
        targetPrct: '20%',
        currentMV: '$48,000',
        currentWeight: '22%',
        source: 'Rebalance',
        trades: '- $3,000',
        postMV: '$45,000',
        postTargetPrct: '20%',
      },
      { 
        assetName: 'Manulife Global Equity',
        targetPrct: '17.5%',
        currentMV: '$38,000',
        currentWeight: '20%',
        source: 'Rebalance',
        trades: '$0',
        postMV: '$38,000',
        postTargetPrct: '17.5%',
      },
    ],
    fixedIncomeRec: [
      { 
        assetName: 'Fidelity Global Bond',
        targetPrct: '40%',
        currentMV: '$80,000',
        currentWeight: '36%',
        source: 'Rebalance',
        trades: '+ $8,000',
        postMV: '$88,000',
        postTargetPrct: '40%',
      },
    ],
    cashRec: [
      { 
        assetName: 'Dynamic Money Market Fund',
        targetPrct: '2.5%',
        currentMV: '$5,000',
        currentWeight: '2.0%',
        source: 'Rebalance',
        trades: '+ $500',
        postMV: '$5,500',
        postTargetPrct: '2.5%',
      },
    ],
    risk:[
      {
        name: 'High',
        target: '10%',
        actual: '9%',
        postTrade: '10%',
      },
      {
        name: 'Med',
        target: '7%',
        actual: '8%',
        postTrade: '7%',
      },
      {
        name: 'Low',
        target: '5%',
        actual: '5%',
        postTrade: '5%',
      },
    ],
  },
  {
    account: 22392898,
    name: 'Randal White TFSA',
    client: 'Randal White',
    trades: 3,
    value: '$50,000 CAD',
    source: 'Rebalance',
    equitiesPrct: '',
    fixedIncomePrct: '',
    cashPrct: '',
    equitiesRec: [
      {
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    fixedIncomeRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    cashRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    risk:[
      {
        name: 'High',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Med',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Low',
        target: '',
        actual: '',
        postTrade: '',
      },
    ],
  },
  {
    account: 32342353,
    name: 'Stephanie Sanders TFSA',
    client: 'Stephanie Sanders',
    trades: 1,
    value: '$1,000 CAD',
    source: 'Cash Withdrawl',
    equitiesPrct: '',
    fixedIncomePrct: '',
    cashPrct: '',
    equitiesRec: [
      {
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    fixedIncomeRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    cashRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    risk:[
      {
        name: 'High',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Med',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Low',
        target: '',
        actual: '',
        postTrade: '',
      },
    ],
  },
  {
    account: 45345345,
    name: 'Steve Brown RRSP',
    client: 'Steve Brown',
    trades: 3,
    value: '$5,000 CAD',
    source: 'Deposit',
    equitiesPrct: '',
    fixedIncomePrct: '',
    cashPrct: '',
    equitiesRec: [
      {
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    fixedIncomeRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    cashRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    risk:[
      {
        name: 'High',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Med',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Low',
        target: '',
        actual: '',
        postTrade: '',
      },
    ],
  },
  {
    account: 52342345,
    name: 'Christopher Nolan TFSA',
    client: 'Christopher Nolan',
    trades: 10,
    value: '$1,000,000 CAD',
    source: 'Client Directed',
    equitiesPrct: '',
    fixedIncomePrct: '',
    cashPrct: '',
    equitiesRec: [
      {
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    fixedIncomeRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    cashRec: [
      { 
        assetName: '',
        targetPrct: '',
        currentMV: '',
        currentWeight: '',
        source: '',
        trades: '',
        postMV: '',
        postTargetPrct: '',
      },
    ],
    risk:[
      {
        name: 'High',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Med',
        target: '',
        actual: '',
        postTrade: '',
      },
      {
        name: 'Low',
        target: '',
        actual: '',
        postTrade: '',
      },
    ],
  },
];
export default PendingTradesData;